from fastapi import APIRouter, Query
from typing import Optional
from ..config import settings
from ..services.weather_service import weather_service
from ..services.cloud_models import CloudAIService

router = APIRouter(prefix="/api/weather", tags=["Weather"])

@router.get("/current")
async def get_current_weather(
    lat: Optional[float] = Query(None, description="Latitude from GPS (preferred for hyper-local data)"),
    lon: Optional[float] = Query(None, description="Longitude from GPS (preferred for hyper-local data)"),
    city: Optional[str] = Query(None, description="City or district name (used when no GPS fix)"),
):
    """Return current weather + 3-day forecast for the farmer's location.

    Location is client-driven: GPS coordinates when available, otherwise the
    selected district/city name (fuzzy-matched). Falls back to static data when
    the live providers are unreachable.
    """
    return await weather_service.get_current(lat=lat, lon=lon, city=city)


def _build_rule_advisory(weather: dict, crop: Optional[str]) -> str:
    """Server-side rule-based fallback mirroring the app's client-side advisory."""
    crop_text = crop or "crops"
    parts = []

    def pct(v):
        return None if v is None else round(v)

    temp = weather.get("temperature_c")
    hum = pct(weather.get("humidity"))
    rain = pct(weather.get("rain_probability"))
    wind = pct(weather.get("wind_speed_kmh"))
    uv = pct(weather.get("uv_index"))
    dew = pct(weather.get("dew_point_c"))

    if hum is not None and hum >= 70:
        parts.append(f"High humidity ({hum}%) — watch {crop_text} for fungal diseases like blight and rust; avoid evening overhead irrigation.")
    if rain is not None and rain >= 60:
        parts.append(f"Rain likely ({rain}%) — delay pesticide/fertilizer spraying; harvest ripe {crop_text} early.")
    if wind is not None and wind >= 25:
        parts.append(f"Strong winds ({wind} km/h) — avoid spraying to prevent pesticide drift.")
    if uv is not None and uv >= 7:
        parts.append(f"High UV ({uv}) — heat stress risk for young seedlings; irrigate in cooler hours.")
    if temp is not None and temp >= 35:
        parts.append(f"Very hot ({temp}°C) — irrigate early morning and mulch to keep soil moisture.")
    if temp is not None and temp <= 10:
        parts.append(f"Cold ({temp}°C) — protect young plants from frost with light mulch or covers.")
    if dew is not None and dew >= 20:
        parts.append(f"High dew point ({dew}°C) — morning dew favors rust; scout {crop_text} for pustules.")

    return " ".join(parts) if parts else (
        f"Conditions are favorable for routine field work in {crop_text} — spraying and irrigation are safe."
    )


@router.get("/advisory")
async def get_weather_advisory(
    lat: Optional[float] = Query(None, description="Latitude from GPS (preferred for hyper-local data)"),
    lon: Optional[float] = Query(None, description="Longitude from GPS (preferred for hyper-local data)"),
    city: Optional[str] = Query(None, description="City or district name (used when no GPS fix)"),
    crop: Optional[str] = Query(None, description="Crop being grown (e.g. wheat, rice)"),
    lang: Optional[str] = Query("en", description="Response language: 'en' or 'hi'"),
):
    """LLM-generated field advisory from live weather, with a rule-based fallback.

    Reuses the existing synthesis pipeline (CloudAIService.synthesize_response)
    so the advisory is generated by Gemini 2.5 Flash when configured, otherwise
    by the deterministic rule-based fallback above (mirrors the mobile app's
    buildAdvisory logic).
    """
    weather = await weather_service.get_current(lat=lat, lon=lon, city=city)

    metrics = {
        "temperature_c": weather.get("temperature_c"),
        "condition": weather.get("condition"),
        "humidity_pct": weather.get("humidity"),
        "rainfall_mm": weather.get("precipitation_mm"),
        "rain_probability_pct": weather.get("rain_probability"),
        "wind_speed_kmh": weather.get("wind_speed_kmh"),
        "dew_point_c": weather.get("dew_point_c"),
        "uv_index": weather.get("uv_index"),
        "location": weather.get("location"),
    }
    live_str = " | ".join(f"{k}: {v}" for k, v in metrics.items() if v is not None)
    live_data = {"weather": live_str} if live_str else None

    crop_text = crop or "the farmer's field"
    lang_instruction = "in simple Hindi (Devanagari)" if lang and lang.startswith("hi") else "in simple English"
    query = (
        f"Based ONLY on today's live weather conditions, give the farmer 2-3 short, "
        f"practical field advisory tips for {crop_text} {lang_instruction}. "
        f"Do not invent facts that are not backed by the Live Data."
    )

    if settings.GEMINI_API_KEY and not settings.MOCK_MODELS:
        try:
            answer = await CloudAIService.synthesize_response(query, [], live_data=live_data)
            # The synthesis pipeline falls back to a sell-vs-keep mock internally;
            # treat that as "not a real advisory" and use the rule-based fallback.
            if not answer or "Based on today's live data" in answer:
                raise ValueError("synthesis fell back to its internal mock")
            return {
                "advisory": answer.strip(),
                "source": "llm",
                "crop": crop,
                "location": weather.get("location"),
            }
        except Exception as e:
            print(f"Weather advisory LLM failed ({e}). Using rule-based fallback.")

    return {
        "advisory": _build_rule_advisory(weather, crop),
        "source": "rule",
        "crop": crop,
        "location": weather.get("location"),
    }